// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnGB8g17xVgEu0kvjM1qc8dmJ1aHj0_Ic',
    appId: '1:477459495948:web:77f497d40c1d79dbd20229',
    messagingSenderId: '477459495948',
    projectId: 'islamicquiz-83516',
    authDomain: 'islamicquiz-83516.firebaseapp.com',
    storageBucket: 'islamicquiz-83516.firebasestorage.app',
    measurementId: 'G-V49X8CTP24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG4UtLTW01HgQPZ_ap47ypodlZzJ-ISD0',
    appId: '1:477459495948:android:ed62bd44baf1938dd20229',
    messagingSenderId: '477459495948',
    projectId: 'islamicquiz-83516',
    storageBucket: 'islamicquiz-83516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL2A1v2UjvdaHI7bE1m-HmHxDF_6EJX7Y',
    appId: '1:477459495948:ios:0574d7e3ed079e1bd20229',
    messagingSenderId: '477459495948',
    projectId: 'islamicquiz-83516',
    storageBucket: 'islamicquiz-83516.firebasestorage.app',
    iosClientId: '477459495948-sqblj7n1ue4hnhdtpkbpkh1c7i6m6hrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL2A1v2UjvdaHI7bE1m-HmHxDF_6EJX7Y',
    appId: '1:477459495948:ios:0574d7e3ed079e1bd20229',
    messagingSenderId: '477459495948',
    projectId: 'islamicquiz-83516',
    storageBucket: 'islamicquiz-83516.firebasestorage.app',
    iosClientId: '477459495948-sqblj7n1ue4hnhdtpkbpkh1c7i6m6hrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnGB8g17xVgEu0kvjM1qc8dmJ1aHj0_Ic',
    appId: '1:477459495948:web:754fb876424c6a66d20229',
    messagingSenderId: '477459495948',
    projectId: 'islamicquiz-83516',
    authDomain: 'islamicquiz-83516.firebaseapp.com',
    storageBucket: 'islamicquiz-83516.firebasestorage.app',
    measurementId: 'G-FXHPKKCBJ1',
  );
}
